import type { Metadata } from "next";
import "./globals.css";
import { PlayerEventBrokerProvider } from "@/components/context/PlayerEventBroker";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <PlayerEventBrokerProvider>
          {children}
        </PlayerEventBrokerProvider>
      </body>
    </html>
  );
}
